import { BarChart3, CircleDollarSign, PackageSearch, Receipt } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requireRole } from "@/lib/auth/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { formatCurrency } from "@/lib/pos/types";

export default async function ReportsPage() {
  const context = await requireRole("admin");
  const admin = createAdminClient(); const today = new Date(); today.setHours(0, 0, 0, 0);
  const [{ data: orders }, { data: expenses }, { data: items }] = await Promise.all([admin.from("orders").select("id, total, discount_total").eq("branch_id", context.profile.branchId).eq("status", "paid").gte("paid_at", today.toISOString()), admin.from("expenses").select("amount").eq("branch_id", context.profile.branchId).eq("status", "active").eq("expense_date", today.toISOString().slice(0, 10)), admin.from("order_items").select("product_name_snapshot, quantity, estimated_cost_snapshot, line_total, order_id").eq("branch_id", context.profile.branchId).order("created_at", { ascending: false }).limit(1000)]);
  const paidOrders = (orders ?? []) as Array<{ id: string; total: number; discount_total: number }>;
  const expenseRows = (expenses ?? []) as Array<{ amount: number }>;
  const itemRows = (items ?? []) as Array<{ product_name_snapshot: string; quantity: number; estimated_cost_snapshot: number; line_total: number; order_id: string }>;
  const sales = paidOrders.reduce((sum, order) => sum + Number(order.total), 0); const cost = itemRows.filter((item) => paidOrders.some((order) => order.id === item.order_id)).reduce((sum, item) => sum + Number(item.estimated_cost_snapshot) * Number(item.quantity), 0); const expensesTotal = expenseRows.reduce((sum, expense) => sum + Number(expense.amount), 0); const gross = sales - cost; const net = gross - expensesTotal;
  const topProducts = Object.entries(itemRows.filter((item) => paidOrders.some((order) => order.id === item.order_id)).reduce<Record<string, number>>((result, item) => { result[item.product_name_snapshot] = (result[item.product_name_snapshot] ?? 0) + Number(item.quantity); return result; }, {})).sort(([, a], [, b]) => b - a).slice(0, 8);
  return <div className="mx-auto max-w-7xl space-y-6"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-brand-olive">Lectura del negocio</p><h1 className="mt-2 font-display text-4xl font-bold">Reportes</h1><p className="mt-2 text-brand-olive">Resumen de hoy. El costo de producto es estimado hasta contar con recetas e inventario.</p></div><Badge variant="muted">Hoy</Badge></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Ventas" value={formatCurrency(sales)} icon={CircleDollarSign} /><Metric title="Costo estimado" value={formatCurrency(cost)} icon={PackageSearch} /><Metric title="Ganancia bruta" value={formatCurrency(gross)} icon={BarChart3} /><Metric title="Ganancia neta" value={formatCurrency(net)} icon={Receipt} /></section><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><Card><CardHeader><CardTitle>Productos más vendidos</CardTitle></CardHeader><CardContent className="space-y-3">{topProducts.length ? topProducts.map(([name, quantity], index) => <div key={name} className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-brand-cream text-sm font-bold">{index + 1}</span><span className="flex-1 text-sm font-semibold">{name}</span><span className="text-sm text-brand-olive">{quantity} und.</span></div>) : <p className="py-8 text-center text-sm text-brand-olive">No hay ventas suficientes.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Gastos de hoy</CardTitle></CardHeader><CardContent><p className="font-display text-3xl font-bold">{formatCurrency(expensesTotal)}</p><p className="mt-2 text-sm text-brand-olive">{expenseRows.length} registros activos</p></CardContent></Card></div></div>;
}

function Metric({ title, value, icon: Icon }: { title: string; value: string; icon: typeof CircleDollarSign }) { return <Card><CardContent className="pt-5"><Icon className="size-5 text-brand-gold" /><p className="mt-4 text-sm text-brand-olive">{title}</p><p className="mt-1 font-display text-2xl font-bold">{value}</p></CardContent></Card>; }

