type TableDefinition<Row extends Record<string, unknown>> = {
  Row: Row;
  Insert: Partial<Row>;
  Update: Partial<Row>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      [tableName: string]: TableDefinition<Record<string, unknown>>;
      staff_members: TableDefinition<{
        id: string;
        branch_id: string;
        full_name: string;
        role_key: string;
        pin_hash: string;
        status: string;
        failed_pin_attempts: number;
        locked_until: string | null;
        last_login_at: string | null;
        created_by: string | null;
        updated_by: string | null;
        created_at: string;
        updated_at: string;
      }>;
      staff_sessions: TableDefinition<{
        id: string;
        staff_member_id: string;
        token_hash: string;
        expires_at: string;
        last_seen_at: string;
        revoked_at: string | null;
        ip_address: string | null;
        user_agent: string | null;
        created_at: string;
      }>;
      orders: TableDefinition<{
        id: string;
        branch_id: string;
        order_code: string;
        order_type: string;
        table_id: string | null;
        parent_order_id: string | null;
        waiter_id: string;
        people_count: number | null;
        customer_name: string | null;
        notes: string | null;
        total: number;
        status: string;
        subtotal: number;
        discount_total: number;
        payment_total: number;
        balance_due: number;
        idempotency_key: string;
        opened_at: string;
        sent_to_kitchen_at: string | null;
        delivered_at: string | null;
        paid_at: string | null;
        cancelled_at: string | null;
        created_by: string | null;
        updated_by: string | null;
        created_at: string;
        updated_at: string;
      }>;
      order_items: TableDefinition<{
        id: string;
        branch_id: string;
        order_id: string;
        product_id: string;
        variant_id: string | null;
        product_name_snapshot: string;
        variant_name_snapshot: string | null;
        unit_price: number;
        estimated_cost_snapshot: number;
        quantity: number;
        modifiers_total: number;
        line_total: number;
        notes: string | null;
        priority: string;
        status: string;
        sent_to_kitchen_at: string | null;
        cancelled_at: string | null;
        cancellation_reason: string | null;
        created_by: string | null;
        updated_by: string | null;
        created_at: string;
        updated_at: string;
      }>;
      cash_sessions: TableDefinition<{
        id: string;
        branch_id: string;
        cashier_id: string;
        opening_amount: number;
        expected_amount: number | null;
        counted_amount: number | null;
        difference: number | null;
        opening_note: string | null;
        closing_note: string | null;
        status: string;
        opened_at: string;
        closed_at: string | null;
        created_by: string | null;
        updated_by: string | null;
        created_at: string;
        updated_at: string;
      }>;
      payments: TableDefinition<{
        id: string;
        branch_id: string;
        order_id: string;
        cash_session_id: string | null;
        method: string;
        amount: number;
        received_amount: number | null;
        change_amount: number;
        currency: string;
        operation_number: string | null;
        idempotency_key: string;
        status: string;
        notes: string | null;
        rejection_reason: string | null;
        registered_by: string;
        verified_by: string | null;
        registered_at: string;
        verified_at: string | null;
        created_at: string;
        updated_at: string;
      }>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
